package sqlserver

import (
	discoverySQLServer "blueprint/database/discovery/SQLServer"
	sqlserverModels "blueprint/database/discovery/SQLServer/models"
	sqlserverQueries "blueprint/database/discovery/SQLServer/queries"
	discoveryModels "blueprint/database/discovery/models"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"gorm.io/gorm"
)

type migrationStatement struct {
	order int
	key   string
	sql   string
}

func GenerateMigration(dbSource *gorm.DB, dbTarget *gorm.DB, outputPath string) error {
	statements := make([]migrationStatement, 0)

	addObjectMigrations(&statements, dbSource, dbTarget)
	addTableMigrations(&statements, dbSource, dbTarget)
	addColumnMigrationTODOs(&statements, dbSource, dbTarget)
	addForeignKeyMigrations(&statements, dbSource, dbTarget)

	sort.SliceStable(statements, func(i, j int) bool {
		if statements[i].order != statements[j].order {
			return statements[i].order < statements[j].order
		}
		return statements[i].key < statements[j].key
	})

	var output strings.Builder
	output.WriteString("-- Generated by DatabaseBlueprint\n")
	output.WriteString("-- Source is the desired schema; target is the current schema.\n\n")

	if len(statements) == 0 {
		output.WriteString("-- No executable migration changes detected.\n")
	} else {
		for index, statement := range statements {
			if index > 0 {
				output.WriteString("\nGO\n\n")
			}
			output.WriteString("-- ")
			output.WriteString(statement.key)
			output.WriteString("\n")
			output.WriteString(strings.TrimSpace(statement.sql))
			output.WriteString("\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, []byte(output.String()), 0o644); err != nil {
		return err
	}

	fmt.Printf("Migration script written to %s\n", outputPath)
	return nil
}

func addObjectMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	for _, schema := range missingObjects(
		sqlserverQueries.SqlServerSchemas(dbSource),
		sqlserverQueries.SqlServerSchemas(dbTarget),
		func(value sqlserverModels.Schemas) string { return value.Name },
		func(_, _ sqlserverModels.Schemas) bool { return true },
	) {
		*statements = append(*statements, migrationStatement{order: 10, key: "Schema " + schema.Name, sql: discoverySQLServer.BuildSchemaScript(schema) + ";"})
	}

	for _, userType := range missingObjects(
		sqlserverQueries.SqlServerUserDefinedTypes(dbSource),
		sqlserverQueries.SqlServerUserDefinedTypes(dbTarget),
		func(value sqlserverModels.UserDefinedType) string { return value.SchemaName + "." + value.TypeName },
		func(source, target sqlserverModels.UserDefinedType) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 20,
			key:   "User-defined type " + userType.SchemaName + "." + userType.TypeName,
			sql:   discoverySQLServer.BuildUserDefinedTypeScript(userType),
		})
	}

	for _, tableType := range missingObjects(
		sqlserverQueries.SqlServerUserDefinedTableTypes(dbSource),
		sqlserverQueries.SqlServerUserDefinedTableTypes(dbTarget),
		func(value sqlserverModels.UserDefinedTableType) string {
			return value.SchemaName + "." + value.TypeName
		},
		func(source, target sqlserverModels.UserDefinedTableType) bool {
			return reflect.DeepEqual(source, target)
		},
	) {
		*statements = append(*statements, migrationStatement{
			order: 30,
			key:   "Table type " + tableType.SchemaName + "." + tableType.TypeName,
			sql:   discoverySQLServer.BuildTableTypeScript(*dbSource, tableType),
		})
	}

	for _, sequence := range missingObjects(
		sqlserverQueries.SqlServerSequences(dbSource),
		sqlserverQueries.SqlServerSequences(dbTarget),
		func(value sqlserverModels.Sequences) string { return value.SchemaName + "." + value.SequenceName },
		func(source, target sqlserverModels.Sequences) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 40,
			key:   "Sequence " + sequence.SchemaName + "." + sequence.SequenceName,
			sql:   discoverySQLServer.BuildSequenceScript(sequence),
		})
	}
	for _, sequence := range changedObjects(
		sqlserverQueries.SqlServerSequences(dbSource),
		sqlserverQueries.SqlServerSequences(dbTarget),
		func(value sqlserverModels.Sequences) string { return value.SchemaName + "." + value.SequenceName },
		func(source, target sqlserverModels.Sequences) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 41,
			key:   "Sequence " + sequence.SchemaName + "." + sequence.SequenceName,
			sql:   "-- TODO: Generate ALTER SEQUENCE for this changed sequence.",
		})
	}

	for _, synonym := range objectDifferences(
		sqlserverQueries.SqlServerSynonyms(dbSource),
		sqlserverQueries.SqlServerSynonyms(dbTarget),
		func(value sqlserverModels.Synonyms) string { return value.SchemaName + "." + value.SynonymName },
		func(source, target sqlserverModels.Synonyms) bool {
			return source.BaseObjectName == target.BaseObjectName
		},
	) {
		key := synonym.SchemaName + "." + synonym.SynonymName
		_, exists := findObject(sqlserverQueries.SqlServerSynonyms(dbTarget), func(value sqlserverModels.Synonyms) string { return value.SchemaName + "." + value.SynonymName }, key)
		sql := discoverySQLServer.BuildSynonymsScript(synonym)
		if exists {
			sql = fmt.Sprintf("DROP SYNONYM %s.%s;\n%s", quoteIdentifier(synonym.SchemaName), quoteIdentifier(synonym.SynonymName), sql)
		}
		*statements = append(*statements, migrationStatement{order: 70, key: "Synonym " + key, sql: sql})
	}

	addDefinitionMigrations(statements, dbSource, dbTarget)
}

func addDefinitionMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	views := objectDifferences(
		sqlserverQueries.SqlServerViews(*dbSource),
		sqlserverQueries.SqlServerViews(*dbTarget),
		func(value sqlserverModels.Views) string { return value.Schema + "." + value.View },
		func(source, target sqlserverModels.Views) bool { return source.Definition == target.Definition },
	)
	for _, view := range views {
		key := view.Schema + "." + view.View
		*statements = append(*statements, migrationStatement{order: 80, key: "View " + key, sql: alterDefinition(view.Definition)})
	}

	functions := objectDifferences(
		sqlserverQueries.SqlServerFunctions(dbSource),
		sqlserverQueries.SqlServerFunctions(dbTarget),
		func(value sqlserverModels.Functions) string { return value.Schema + "." + value.Name },
		func(source, target sqlserverModels.Functions) bool { return source.Definition == target.Definition },
	)
	for _, function := range functions {
		key := function.Schema + "." + function.Name
		*statements = append(*statements, migrationStatement{order: 90, key: "Function " + key, sql: alterDefinition(function.Definition)})
	}

	procedures := objectDifferences(
		sqlserverQueries.SqlServerProcedures(dbSource),
		sqlserverQueries.SqlServerProcedures(dbTarget),
		func(value sqlserverModels.Procedures) string { return value.Schema + "." + value.Name },
		func(source, target sqlserverModels.Procedures) bool { return source.Definition == target.Definition },
	)
	for _, procedure := range procedures {
		key := procedure.Schema + "." + procedure.Name
		*statements = append(*statements, migrationStatement{order: 100, key: "Procedure " + key, sql: alterDefinition(procedure.Definition)})
	}

	triggers := objectDifferences(
		sqlserverQueries.SqlServerTriggers(dbSource),
		sqlserverQueries.SqlServerTriggers(dbTarget),
		func(value sqlserverModels.Triggers) string { return value.SchemaName + "." + value.TriggerName },
		func(source, target sqlserverModels.Triggers) bool {
			return source.Definition == target.Definition &&
				source.IsInsteadOf == target.IsInsteadOf &&
				source.IsDisabled == target.IsDisabled &&
				source.IsNotForReplication == target.IsNotForReplication
		},
	)
	for _, trigger := range triggers {
		key := trigger.SchemaName + "." + trigger.TriggerName
		*statements = append(*statements, migrationStatement{order: 110, key: "Trigger " + key, sql: discoverySQLServer.BuildTriggerScript(trigger)})
	}
}

func addTableMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	tables := missingObjects(
		sqlserverQueries.SqlServerTables(*dbSource),
		sqlserverQueries.SqlServerTables(*dbTarget),
		func(value discoveryModels.Tables) string { return value.Schema + "." + value.Name },
		func(_, _ discoveryModels.Tables) bool { return true },
	)
	for _, table := range tables {
		key := table.Schema + "." + table.Name
		*statements = append(*statements, migrationStatement{order: 50, key: "Table " + key, sql: discoverySQLServer.BuildTableScript(*dbSource, table.Schema, table.Name)})
	}
}

func addColumnMigrationTODOs(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	sourceTables := sqlserverQueries.SqlServerTables(*dbSource)
	targetTables := sqlserverQueries.SqlServerTables(*dbTarget)
	targetTableMap := make(map[string]struct{}, len(targetTables))
	for _, table := range targetTables {
		targetTableMap[table.Schema+"."+table.Name] = struct{}{}
	}

	for _, table := range sourceTables {
		tableKey := table.Schema + "." + table.Name
		if _, exists := targetTableMap[tableKey]; !exists {
			continue
		}

		sourceColumns := sqlserverQueries.SqlServerColumns(dbSource, tableKey)
		targetColumns := sqlserverQueries.SqlServerColumns(dbTarget, tableKey)
		key := func(value sqlserverModels.Column) string { return value.ColumnName }
		equal := func(source, target sqlserverModels.Column) bool { return reflect.DeepEqual(source, target) }

		for _, column := range objectDifferences(sourceColumns, targetColumns, key, equal) {
			*statements = append(*statements, migrationStatement{
				order: 130,
				key:   "Column " + tableKey + "." + column.ColumnName,
				sql:   "-- TODO: Generate ALTER TABLE for this changed column.",
			})
		}
	}
}

func addForeignKeyMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	differences := objectDifferences(
		sqlserverQueries.SqlServerForeignKeys(dbSource),
		sqlserverQueries.SqlServerForeignKeys(dbTarget),
		func(value sqlserverModels.ForeignKeyColumn) string {
			return value.ParentSchema + "." + value.ParentTable + "." + value.ForeignKeyName + "." + fmt.Sprint(value.KeyOrdinal)
		},
		func(source, target sqlserverModels.ForeignKeyColumn) bool {
			return source.ForeignKeyName == target.ForeignKeyName &&
				source.ParentSchema == target.ParentSchema &&
				source.ParentTable == target.ParentTable &&
				source.ColumnName == target.ColumnName &&
				source.KeyOrdinal == target.KeyOrdinal &&
				source.ReferencedSchema == target.ReferencedSchema &&
				source.ReferencedTable == target.ReferencedTable &&
				source.ReferencedColumn == target.ReferencedColumn &&
				source.DeleteAction == target.DeleteAction &&
				source.UpdateAction == target.UpdateAction
		},
	)

	grouped := make(map[string][]sqlserverModels.ForeignKeyColumn)
	for _, foreignKey := range differences {
		grouped[foreignKey.ParentSchema+"."+foreignKey.ParentTable+"."+foreignKey.ForeignKeyName] = append(grouped[foreignKey.ParentSchema+"."+foreignKey.ParentTable+"."+foreignKey.ForeignKeyName], foreignKey)
	}

	keys := make([]string, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		for _, definition := range discoverySQLServer.GenerateForeignKeys(grouped[key]) {
			*statements = append(*statements, migrationStatement{order: 120, key: "Foreign key " + key, sql: definition})
		}
	}
}

func objectDifferences[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	targetByKey := make(map[string]T, len(target))
	for _, value := range target {
		targetByKey[key(value)] = value
	}

	differences := make([]T, 0)
	for _, value := range source {
		other, exists := targetByKey[key(value)]
		if !exists || !equal(value, other) {
			differences = append(differences, value)
		}
	}

	return differences
}

func missingObjects[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	_ = equal
	targetByKey := make(map[string]struct{}, len(target))
	for _, value := range target {
		targetByKey[key(value)] = struct{}{}
	}

	missing := make([]T, 0)
	for _, value := range source {
		if _, exists := targetByKey[key(value)]; !exists {
			missing = append(missing, value)
		}
	}
	return missing
}

func changedObjects[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	targetByKey := make(map[string]T, len(target))
	for _, value := range target {
		targetByKey[key(value)] = value
	}

	changed := make([]T, 0)
	for _, value := range source {
		other, exists := targetByKey[key(value)]
		if exists && !equal(value, other) {
			changed = append(changed, value)
		}
	}
	return changed
}

func findObject[T any](objects []T, key func(T) string, wanted string) (T, bool) {
	for _, object := range objects {
		if key(object) == wanted {
			return object, true
		}
	}

	var zero T
	return zero, false
}

func alterDefinition(definition string) string {
	definition = strings.TrimSpace(definition)
	if strings.HasPrefix(strings.ToUpper(definition), "CREATE OR ALTER ") {
		return definition
	}
	if strings.HasPrefix(strings.ToUpper(definition), "CREATE ") {
		return "CREATE OR ALTER " + strings.TrimSpace(definition[len("CREATE "):])
	}
	return "-- Unable to convert definition to CREATE OR ALTER:\n-- " + strings.ReplaceAll(definition, "\n", "\n-- ")
}

func quoteIdentifier(value string) string {
	if value == "" {
		return value
	}
	if strings.HasPrefix(value, "[") || strings.ContainsAny(value, ".\"'") {
		return value
	}

	for _, character := range value {
		if !(unicode.IsLetter(character) || unicode.IsDigit(character) || character == '_') {
			return "[" + strings.ReplaceAll(value, "]", "]]") + "]"
		}
	}
	return "[" + strings.ReplaceAll(value, "]", "]]") + "]"
}
