package sqlserver

import (
	discoverySQLServer "blueprint/database/discovery/SQLServer"
	sqlserverModels "blueprint/database/discovery/SQLServer/models"
	sqlserverQueries "blueprint/database/discovery/SQLServer/queries"
	discoveryModels "blueprint/database/discovery/models"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"gorm.io/gorm"
)

type migrationStatement struct {
	order int
	key   string
	sql   string
}

func GenerateMigration(dbSource *gorm.DB, dbTarget *gorm.DB, outputPath string) error {
	statements := make([]migrationStatement, 0)

	addObjectMigrations(&statements, dbSource, dbTarget)
	addTableMigrations(&statements, dbSource, dbTarget)
	addColumnMigrations(&statements, dbSource, dbTarget)
	addDefaultConstraintMigrations(&statements, dbSource, dbTarget)
	addConstraintMigrations(&statements, dbSource, dbTarget)
	addForeignKeyMigrations(&statements, dbSource, dbTarget)

	sort.SliceStable(statements, func(i, j int) bool {
		if statements[i].order != statements[j].order {
			return statements[i].order < statements[j].order
		}
		return statements[i].key < statements[j].key
	})

	var output strings.Builder
	output.WriteString("-- Generated by DatabaseBlueprint\n")
	output.WriteString("-- Source is the desired schema; target is the current schema.\n\n")

	if len(statements) == 0 {
		output.WriteString("-- No executable migration changes detected.\n")
	} else {
		for index, statement := range statements {
			if index > 0 {
				output.WriteString("\nGO\n\n")
			}
			if !isModuleMigration(statement.key) {
				output.WriteString("-- ")
				output.WriteString(statement.key)
				output.WriteString("\n")
			}
			output.WriteString(strings.TrimSpace(statement.sql))
			output.WriteString("\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, []byte(output.String()), 0o644); err != nil {
		return err
	}

	fmt.Printf("Migration script written to %s\n", outputPath)
	return nil
}

func isModuleMigration(key string) bool {
	return strings.HasPrefix(key, "View ") ||
		strings.HasPrefix(key, "Function ") ||
		strings.HasPrefix(key, "Procedure ") ||
		strings.HasPrefix(key, "Trigger ")
}

func addObjectMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	for _, schema := range missingObjects(
		sqlserverQueries.SqlServerSchemas(dbSource),
		sqlserverQueries.SqlServerSchemas(dbTarget),
		func(value sqlserverModels.Schemas) string { return value.Name },
		func(_, _ sqlserverModels.Schemas) bool { return true },
	) {
		*statements = append(*statements, migrationStatement{order: 10, key: "Schema " + schema.Name, sql: discoverySQLServer.BuildSchemaScript(schema) + ";"})
	}

	for _, userType := range missingObjects(
		sqlserverQueries.SqlServerUserDefinedTypes(dbSource),
		sqlserverQueries.SqlServerUserDefinedTypes(dbTarget),
		func(value sqlserverModels.UserDefinedType) string { return value.SchemaName + "." + value.TypeName },
		func(source, target sqlserverModels.UserDefinedType) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 20,
			key:   "User-defined type " + userType.SchemaName + "." + userType.TypeName,
			sql:   discoverySQLServer.BuildUserDefinedTypeScript(userType),
		})
	}

	for _, tableType := range missingObjects(
		sqlserverQueries.SqlServerUserDefinedTableTypes(dbSource),
		sqlserverQueries.SqlServerUserDefinedTableTypes(dbTarget),
		func(value sqlserverModels.UserDefinedTableType) string {
			return value.SchemaName + "." + value.TypeName
		},
		func(source, target sqlserverModels.UserDefinedTableType) bool {
			return reflect.DeepEqual(source, target)
		},
	) {
		*statements = append(*statements, migrationStatement{
			order: 30,
			key:   "Table type " + tableType.SchemaName + "." + tableType.TypeName,
			sql:   discoverySQLServer.BuildTableTypeScript(*dbSource, tableType),
		})
	}

	for _, sequence := range missingObjects(
		sqlserverQueries.SqlServerSequences(dbSource),
		sqlserverQueries.SqlServerSequences(dbTarget),
		func(value sqlserverModels.Sequences) string { return value.SchemaName + "." + value.SequenceName },
		func(source, target sqlserverModels.Sequences) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 40,
			key:   "Sequence " + sequence.SchemaName + "." + sequence.SequenceName,
			sql:   discoverySQLServer.BuildSequenceScript(sequence),
		})
	}
	for _, sequence := range changedObjects(
		sqlserverQueries.SqlServerSequences(dbSource),
		sqlserverQueries.SqlServerSequences(dbTarget),
		func(value sqlserverModels.Sequences) string { return value.SchemaName + "." + value.SequenceName },
		func(source, target sqlserverModels.Sequences) bool { return reflect.DeepEqual(source, target) },
	) {
		*statements = append(*statements, migrationStatement{
			order: 41,
			key:   "Sequence " + sequence.SchemaName + "." + sequence.SequenceName,
			sql:   "-- TODO: Generate ALTER SEQUENCE for this changed sequence.",
		})
	}

	for _, synonym := range objectDifferences(
		sqlserverQueries.SqlServerSynonyms(dbSource),
		sqlserverQueries.SqlServerSynonyms(dbTarget),
		func(value sqlserverModels.Synonyms) string { return value.SchemaName + "." + value.SynonymName },
		func(source, target sqlserverModels.Synonyms) bool {
			return source.BaseObjectName == target.BaseObjectName
		},
	) {
		key := synonym.SchemaName + "." + synonym.SynonymName
		_, exists := findObject(sqlserverQueries.SqlServerSynonyms(dbTarget), func(value sqlserverModels.Synonyms) string { return value.SchemaName + "." + value.SynonymName }, key)
		sql := discoverySQLServer.BuildSynonymsScript(synonym)
		if exists {
			sql = fmt.Sprintf("DROP SYNONYM %s.%s;\n%s", quoteIdentifier(synonym.SchemaName), quoteIdentifier(synonym.SynonymName), sql)
		}
		*statements = append(*statements, migrationStatement{order: 70, key: "Synonym " + key, sql: sql})
	}

	addDefinitionMigrations(statements, dbSource, dbTarget)
}

func addDefinitionMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	views := objectDifferences(
		sqlserverQueries.SqlServerViews(*dbSource),
		sqlserverQueries.SqlServerViews(*dbTarget),
		func(value sqlserverModels.Views) string { return value.Schema + "." + value.View },
		func(source, target sqlserverModels.Views) bool {
			return definitionsEqual(source.Definition, target.Definition)
		},
	)
	for _, view := range views {
		key := view.Schema + "." + view.View
		*statements = append(*statements, migrationStatement{order: 80, key: "View " + key, sql: alterDefinition(view.Definition)})
	}

	functions := objectDifferences(
		sqlserverQueries.SqlServerFunctions(dbSource),
		sqlserverQueries.SqlServerFunctions(dbTarget),
		func(value sqlserverModels.Functions) string { return value.Schema + "." + value.Name },
		func(source, target sqlserverModels.Functions) bool {
			return definitionsEqual(source.Definition, target.Definition)
		},
	)
	for _, function := range functions {
		key := function.Schema + "." + function.Name
		*statements = append(*statements, migrationStatement{order: 90, key: "Function " + key, sql: alterDefinition(function.Definition)})
	}

	procedures := objectDifferences(
		sqlserverQueries.SqlServerProcedures(dbSource),
		sqlserverQueries.SqlServerProcedures(dbTarget),
		func(value sqlserverModels.Procedures) string { return value.Schema + "." + value.Name },
		func(source, target sqlserverModels.Procedures) bool {
			return definitionsEqual(source.Definition, target.Definition)
		},
	)
	for _, procedure := range procedures {
		key := procedure.Schema + "." + procedure.Name
		*statements = append(*statements, migrationStatement{order: 100, key: "Procedure " + key, sql: alterDefinition(procedure.Definition)})
	}

	triggers := objectDifferences(
		sqlserverQueries.SqlServerTriggers(dbSource),
		sqlserverQueries.SqlServerTriggers(dbTarget),
		func(value sqlserverModels.Triggers) string { return value.SchemaName + "." + value.TriggerName },
		func(source, target sqlserverModels.Triggers) bool {
			return definitionsEqual(source.Definition, target.Definition) &&
				source.IsInsteadOf == target.IsInsteadOf &&
				source.IsDisabled == target.IsDisabled &&
				source.IsNotForReplication == target.IsNotForReplication
		},
	)
	for _, trigger := range triggers {
		key := trigger.SchemaName + "." + trigger.TriggerName
		sql := alterDefinition(trigger.Definition)
		if trigger.IsDisabled {
			sql += fmt.Sprintf(
				"\n\nDISABLE TRIGGER %s.%s ON %s.%s;",
				quoteIdentifier(trigger.SchemaName),
				quoteIdentifier(trigger.TriggerName),
				quoteIdentifier(trigger.TableSchemaName),
				quoteIdentifier(trigger.TableName),
			)
		}
		*statements = append(*statements, migrationStatement{order: 110, key: "Trigger " + key, sql: sql})
	}
}

func addTableMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	tables := missingObjects(
		sqlserverQueries.SqlServerTables(*dbSource),
		sqlserverQueries.SqlServerTables(*dbTarget),
		func(value discoveryModels.Tables) string { return value.Schema + "." + value.Name },
		func(_, _ discoveryModels.Tables) bool { return true },
	)
	for _, table := range tables {
		key := table.Schema + "." + table.Name
		*statements = append(*statements, migrationStatement{order: 50, key: "Table " + key, sql: discoverySQLServer.BuildTableScript(*dbSource, table.Schema, table.Name)})
	}
}

func addColumnMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	sourceTables := sqlserverQueries.SqlServerTables(*dbSource)
	targetTables := sqlserverQueries.SqlServerTables(*dbTarget)
	targetTableMap := make(map[string]struct{}, len(targetTables))
	for _, table := range targetTables {
		targetTableMap[table.Schema+"."+table.Name] = struct{}{}
	}

	for _, table := range sourceTables {
		tableKey := table.Schema + "." + table.Name
		if _, exists := targetTableMap[tableKey]; !exists {
			continue
		}

		sourceColumns := sqlserverQueries.SqlServerColumns(dbSource, tableKey)
		targetColumns := sqlserverQueries.SqlServerColumns(dbTarget, tableKey)
		targetColumnMap := make(map[string]sqlserverModels.Column, len(targetColumns))
		for _, column := range targetColumns {
			targetColumnMap[column.ColumnName] = column
		}
		defaultConstraints := sqlserverQueries.SqlServerDefaultConstraints(dbSource, tableKey)
		defaultsByColumnID := make(map[int]sqlserverModels.DefaultConstraint, len(defaultConstraints))
		for _, constraint := range defaultConstraints {
			defaultsByColumnID[constraint.ColumnID] = constraint
		}

		for _, column := range sourceColumns {
			targetColumn, exists := targetColumnMap[column.ColumnName]
			if !exists {
				*statements = append(*statements, migrationStatement{
					order: 55,
					key:   "Column " + tableKey + "." + column.ColumnName,
					sql:   addColumnSQL(table, column, defaultsByColumnID[column.ColumnID]),
				})
				continue
			}

			if reflect.DeepEqual(column, targetColumn) {
				continue
			}

			if !canAlterColumn(column, targetColumn) {
				*statements = append(*statements, migrationStatement{
					order: 55,
					key:   "Column " + tableKey + "." + column.ColumnName,
					sql:   "-- TODO: Generate a safe ALTER TABLE for this identity or computed column change.",
				})
				continue
			}

			*statements = append(*statements, migrationStatement{
				order: 55,
				key:   "Column " + tableKey + "." + column.ColumnName,
				sql:   alterColumnSQL(table, column),
			})
		}
	}
}

func addDefaultConstraintMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	compareExistingTablesForMigration(dbSource, dbTarget, func(table discoveryModels.Tables, tableKey string) {
		sourceDefaults := sqlserverQueries.SqlServerDefaultConstraints(dbSource, tableKey)
		targetDefaults := sqlserverQueries.SqlServerDefaultConstraints(dbTarget, tableKey)
		targetColumns := sqlserverQueries.SqlServerColumns(dbTarget, tableKey)
		targetColumnMap := make(map[string]struct{}, len(targetColumns))
		for _, column := range targetColumns {
			targetColumnMap[column.ColumnName] = struct{}{}
		}
		targetByColumn := make(map[string]sqlserverModels.DefaultConstraint, len(targetDefaults))
		for _, constraint := range targetDefaults {
			targetByColumn[constraint.ColumnName] = constraint
		}

		for _, source := range sourceDefaults {
			if _, exists := targetColumnMap[source.ColumnName]; !exists {
				continue
			}
			target, exists := targetByColumn[source.ColumnName]
			if exists && source.ConstraintValue == target.ConstraintValue &&
				source.IsSystemNamed == target.IsSystemNamed &&
				(source.IsSystemNamed || source.ConstraintName == target.ConstraintName) {
				continue
			}

			sql := addDefaultConstraintSQL(table, source)
			if exists {
				sql = fmt.Sprintf("ALTER TABLE %s.%s DROP CONSTRAINT %s;\n%s", quoteIdentifier(table.Schema), quoteIdentifier(table.Name), quoteIdentifier(target.ConstraintName), sql)
			}

			*statements = append(*statements, migrationStatement{
				order: 60,
				key:   "Default " + tableKey + "." + source.ColumnName,
				sql:   sql,
			})
		}
	})
}

func compareExistingTablesForMigration(dbSource *gorm.DB, dbTarget *gorm.DB, compare func(discoveryModels.Tables, string)) {
	sourceTables := sqlserverQueries.SqlServerTables(*dbSource)
	targetTables := sqlserverQueries.SqlServerTables(*dbTarget)
	targetTableMap := make(map[string]struct{}, len(targetTables))
	for _, table := range targetTables {
		targetTableMap[table.Schema+"."+table.Name] = struct{}{}
	}

	for _, table := range sourceTables {
		tableKey := table.Schema + "." + table.Name
		if _, exists := targetTableMap[tableKey]; exists {
			compare(table, tableKey)
		}
	}
}

func addColumnSQL(table discoveryModels.Tables, column sqlserverModels.Column, defaultConstraint sqlserverModels.DefaultConstraint) string {
	definition := columnDefinitionSQL(column, defaultConstraint)
	return fmt.Sprintf("ALTER TABLE %s.%s ADD %s;", quoteIdentifier(table.Schema), quoteIdentifier(table.Name), definition)
}

func alterColumnSQL(table discoveryModels.Tables, column sqlserverModels.Column) string {
	nullability := "NOT NULL"
	if column.IsNullable {
		nullability = "NULL"
	}
	return fmt.Sprintf(
		"ALTER TABLE %s.%s ALTER COLUMN %s %s %s;",
		quoteIdentifier(table.Schema),
		quoteIdentifier(table.Name),
		quoteIdentifier(column.ColumnName),
		columnDataTypeSQL(column),
		nullability,
	)
}

func addDefaultConstraintSQL(table discoveryModels.Tables, constraint sqlserverModels.DefaultConstraint) string {
	constraintName := ""
	if constraint.ConstraintName != "" && !constraint.IsSystemNamed {
		constraintName = " CONSTRAINT " + quoteIdentifier(constraint.ConstraintName)
	}
	return fmt.Sprintf(
		"ALTER TABLE %s.%s ADD%s DEFAULT %s FOR %s;",
		quoteIdentifier(table.Schema),
		quoteIdentifier(table.Name),
		constraintName,
		constraint.ConstraintValue,
		quoteIdentifier(constraint.ColumnName),
	)
}

func columnDefinitionSQL(column sqlserverModels.Column, defaultConstraint sqlserverModels.DefaultConstraint) string {
	if column.ComputedDefinition != "" {
		definition := fmt.Sprintf("%s AS %s", quoteIdentifier(column.ColumnName), column.ComputedDefinition)
		if column.IsPersisted {
			definition += " PERSISTED"
		}
		return definition
	}

	nullability := "NOT NULL"
	if column.IsNullable {
		nullability = "NULL"
	}
	definition := fmt.Sprintf("%s %s", quoteIdentifier(column.ColumnName), columnDataTypeSQL(column))
	if column.IsIdentity {
		definition += fmt.Sprintf(" IDENTITY(%s,%s)", identityValue(column.IdentitySeed, "1"), identityValue(column.IdentityIncrement, "1"))
	}
	definition += " " + nullability
	if defaultConstraint.ConstraintValue != "" {
		if defaultConstraint.ConstraintName != "" && !defaultConstraint.IsSystemNamed {
			definition += " CONSTRAINT " + quoteIdentifier(defaultConstraint.ConstraintName)
		}
		definition += " DEFAULT " + defaultConstraint.ConstraintValue
	}
	return definition
}

func columnDataTypeSQL(column sqlserverModels.Column) string {
	dataType := strings.ToUpper(column.DataType)
	switch strings.ToLower(column.DataType) {
	case "varchar", "char", "varbinary", "binary":
		if column.MaxLength == -1 {
			return dataType + "(MAX)"
		}
		return fmt.Sprintf("%s(%d)", dataType, column.MaxLength)
	case "nvarchar", "nchar":
		if column.MaxLength == -1 {
			return dataType + "(MAX)"
		}
		return fmt.Sprintf("%s(%d)", dataType, column.MaxLength/2)
	case "decimal", "numeric":
		return fmt.Sprintf("%s(%d,%d)", dataType, column.Precision, column.Scale)
	case "datetime2", "datetimeoffset", "time":
		return fmt.Sprintf("%s(%d)", dataType, column.Scale)
	case "timestamp":
		return "ROWVERSION"
	default:
		return dataType
	}
}

func identityValue(value string, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}

func canAlterColumn(source sqlserverModels.Column, target sqlserverModels.Column) bool {
	return source.IsIdentity == target.IsIdentity &&
		!source.IsIdentity && !target.IsIdentity &&
		source.ComputedDefinition == "" && target.ComputedDefinition == ""
}

func addForeignKeyMigrations(statements *[]migrationStatement, dbSource *gorm.DB, dbTarget *gorm.DB) {
	source := groupForeignKeys(sqlserverQueries.SqlServerForeignKeys(dbSource))
	target := groupForeignKeys(sqlserverQueries.SqlServerForeignKeys(dbTarget))

	for key, sourceRows := range source {
		targetRows, exists := target[key]
		if exists && foreignKeyRowsEqual(sourceRows, targetRows) {
			continue
		}

		definitions := discoverySQLServer.GenerateForeignKeys(sourceRows)
		if exists {
			definitions = append([]string{dropForeignKeySQL(targetRows[0])}, definitions...)
		}

		*statements = append(*statements, migrationStatement{
			order: 120,
			key:   "Foreign key " + key,
			sql:   strings.Join(definitions, "\n"),
		})
	}
}

func groupForeignKeys(rows []sqlserverModels.ForeignKeyColumn) map[string][]sqlserverModels.ForeignKeyColumn {
	return groupRows(rows, func(row sqlserverModels.ForeignKeyColumn) string {
		return row.ParentSchema + "." + row.ParentTable + "." + row.ForeignKeyName
	})
}

func foreignKeyRowsEqual(source []sqlserverModels.ForeignKeyColumn, target []sqlserverModels.ForeignKeyColumn) bool {
	if len(source) != len(target) {
		return false
	}
	for index := range source {
		left := source[index]
		right := target[index]
		if left.ForeignKeyName != right.ForeignKeyName ||
			left.ParentSchema != right.ParentSchema ||
			left.ParentTable != right.ParentTable ||
			left.ColumnName != right.ColumnName ||
			left.KeyOrdinal != right.KeyOrdinal ||
			left.ReferencedSchema != right.ReferencedSchema ||
			left.ReferencedTable != right.ReferencedTable ||
			left.ReferencedColumn != right.ReferencedColumn ||
			left.DeleteAction != right.DeleteAction ||
			left.UpdateAction != right.UpdateAction {
			return false
		}
	}
	return true
}

func dropForeignKeySQL(foreignKey sqlserverModels.ForeignKeyColumn) string {
	return fmt.Sprintf(
		"ALTER TABLE %s.%s DROP CONSTRAINT %s;",
		quoteIdentifier(foreignKey.ParentSchema),
		quoteIdentifier(foreignKey.ParentTable),
		quoteIdentifier(foreignKey.ForeignKeyName),
	)
}

func objectDifferences[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	targetByKey := make(map[string]T, len(target))
	for _, value := range target {
		targetByKey[key(value)] = value
	}

	differences := make([]T, 0)
	for _, value := range source {
		other, exists := targetByKey[key(value)]
		if !exists || !equal(value, other) {
			differences = append(differences, value)
		}
	}

	return differences
}

func missingObjects[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	_ = equal
	targetByKey := make(map[string]struct{}, len(target))
	for _, value := range target {
		targetByKey[key(value)] = struct{}{}
	}

	missing := make([]T, 0)
	for _, value := range source {
		if _, exists := targetByKey[key(value)]; !exists {
			missing = append(missing, value)
		}
	}
	return missing
}

func changedObjects[T any](source []T, target []T, key func(T) string, equal func(T, T) bool) []T {
	targetByKey := make(map[string]T, len(target))
	for _, value := range target {
		targetByKey[key(value)] = value
	}

	changed := make([]T, 0)
	for _, value := range source {
		other, exists := targetByKey[key(value)]
		if exists && !equal(value, other) {
			changed = append(changed, value)
		}
	}
	return changed
}

func findObject[T any](objects []T, key func(T) string, wanted string) (T, bool) {
	for _, object := range objects {
		if key(object) == wanted {
			return object, true
		}
	}

	var zero T
	return zero, false
}

func alterDefinition(definition string) string {
	definition = strings.TrimSpace(definition)
	if strings.HasPrefix(strings.ToUpper(definition), "CREATE OR ALTER ") {
		return definition
	}
	if strings.HasPrefix(strings.ToUpper(definition), "CREATE ") {
		return "CREATE OR ALTER " + strings.TrimSpace(definition[len("CREATE "):])
	}
	return "-- Unable to convert definition to CREATE OR ALTER:\n-- " + strings.ReplaceAll(definition, "\n", "\n-- ")
}

func definitionsEqual(source string, target string) bool {
	return normalizeDefinition(source) == normalizeDefinition(target)
}

func normalizeDefinition(definition string) string {
	definition = strings.TrimSpace(definition)
	upper := strings.ToUpper(definition)
	if strings.HasPrefix(upper, "CREATE OR ALTER ") {
		return "CREATE " + definition[len("CREATE OR ALTER "):]
	}
	return definition
}

func quoteIdentifier(value string) string {
	if value == "" {
		return value
	}
	if strings.HasPrefix(value, "[") || strings.ContainsAny(value, ".\"'") {
		return value
	}

	for _, character := range value {
		if !(unicode.IsLetter(character) || unicode.IsDigit(character) || character == '_') {
			return "[" + strings.ReplaceAll(value, "]", "]]") + "]"
		}
	}
	return "[" + strings.ReplaceAll(value, "]", "]]") + "]"
}
